//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse_Manager.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WAREHOUSE_MANAGEREntities : DbContext
    {
        public WAREHOUSE_MANAGEREntities()
            : base("name=WAREHOUSE_MANAGEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<INPUT> INPUT { get; set; }
        public virtual DbSet<INPUT_DETAIL> INPUT_DETAIL { get; set; }
        public virtual DbSet<OBJECT_TYPE> OBJECT_TYPE { get; set; }
        public virtual DbSet<OUTPUT> OUTPUT { get; set; }
        public virtual DbSet<OUTPUT_DETAIL> OUTPUT_DETAIL { get; set; }
        public virtual DbSet<SUPLIER> SUPLIER { get; set; }
        public virtual DbSet<UNIT> UNIT { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
