//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse_Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPUT_DETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INPUT_DETAIL()
        {
            this.OUTPUT_DETAIL = new HashSet<OUTPUT_DETAIL>();
        }
    
        public int ID { get; set; }
        public string INPUT_ID { get; set; }
        public Nullable<int> OBJECT_TYPE_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> SUPLIER_ID { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<long> IN_PRICE { get; set; }
        public Nullable<long> OUT_PRICE { get; set; }
    
        public virtual INPUT INPUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTPUT_DETAIL> OUTPUT_DETAIL { get; set; }
        public virtual OBJECT_TYPE OBJECT_TYPE { get; set; }
        public virtual SUPLIER SUPLIER { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
