//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WareHouse_Manager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OUTPUT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OUTPUT()
        {
            this.OUTPUT_DETAIL = new HashSet<OUTPUT_DETAIL>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> DATE_OUTPUT { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUTPUT_DETAIL> OUTPUT_DETAIL { get; set; }
    }
}
